version: "3.8"
services:
  zerepy:
    build: .
    container_name: zerepy
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
    networks:
      - zerepy-network

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    ports:
      - "5672:5672"   # AMQP port
      - "15672:15672" # Management console port (optional)
    networks:
      - zerepy-network

networks:
  zerepy-network:
    driver: bridge